@echo off 
DOSKEY ls=dir /B $*
DOSKEY pwd=cd
DOSKEY cd=cd $*
DOSKEY mkdir=mkdir $*
DOSKEY rmdir=rmdir $*
DOSKEY rm=del $*
DOSKEY rmrf=rmdir /S /Q $*
DOSKEY cp=copy $*
DOSKEY cpr=xcopy $* /E
DOSKEY mv=move $*
DOSKEY cat=type $*
DOSKEY less=more $*
DOSKEY grep=findstr $*
DOSKEY grepr=findstr /S $*
DOSKEY find=dir /s $*
DOSKEY ps=tasklist $*
DOSKEY kill=taskkill /PID $*
DOSKEY top=taskmgr
DOSKEY whoami=whoami
DOSKEY ip=ipconfig $*
DOSKEY ipr=route print
DOSKEY ping=ping $*
DOSKEY ss=netstat -ano
DOSKEY curl=curl $*
DOSKEY ifconfig=ipconfig
DOSKEY kali=ssh kali@192.168.56.133
DOSKEY mobsf=docker run -it --rm -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest
DOSKEY semgrep=docker run --rm -v "%cd%:/src" returntocorp/semgrep semgrep $*
